name: Deploy to VM

on:
  push:
    branches:
      - main   # change if you want a different branch to trigger deploys

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout repo ---
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Authenticate with GCP using Service Account Key ---
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # --- Configure Docker to use gcloud as credential helper ---
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # --- Build and Push Docker image ---
      - name: Build & Push Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/newservice-repo/newservice:latest
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # --- Deploy on VM ---
      - name: Deploy on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/newservice-repo/newservice:latest
            docker stop newservice || true
            docker rm newservice || true
            docker pull $IMAGE_NAME
            docker run -d \
              -p 8080:8080 \
              --restart=always \
              --env-file /home/kushal/.env \
              --name newservice \
              $IMAGE_NAME
          EOF
