name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: news-tts-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Enable required Google APIs
        run: |
          gcloud services enable run.googleapis.com
          gcloud services enable containerregistry.googleapis.com
          gcloud services enable cloudbuild.googleapis.com

      - name: Configure Docker for Google Container Registry
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
          flags: |
            --memory=8Gi
            --cpu=4
            --timeout=900
            --concurrency=50
            --max-instances=5
            --startup-cpu-boost
            --execution-environment=gen2
            --port=8080
          env_vars: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            FIREBASE_SERVICE_ACCOUNT_BASE64=${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
            FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
            ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}
            CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}
            LOG_LEVEL=${{ secrets.LOG_LEVEL }}

      - name: Show deployment success
        run: |
          echo "🚀 Deployed successfully!"
          echo "🌐 Service URL: https://${{ env.SERVICE_NAME }}-${{ hashFiles('**') }}-uc.a.run.app"
          echo "📘 Docs: https://${{ env.SERVICE_NAME }}-${{ hashFiles('**') }}-uc.a.run.app/docs"
          echo "💚 Health: https://${{ env.SERVICE_NAME }}-${{ hashFiles('**') }}-uc.a.run.app/health"