name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔑 Authenticate with Google Cloud using service account JSON
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 🐳 Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev -q

      # 📦 Build & Push Docker image
      - name: Build & Push Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/newservice-repo/newservice:latest
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 🚀 Deploy to VM via SSH
      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/newservice-repo/newservice:latest

            echo "🛑 Stopping old container..."
            docker stop newservice || true
            docker rm newservice || true

            echo "📥 Pulling latest image..."
            docker pull $IMAGE_NAME

            echo "🚀 Starting new container..."
            docker run -d \
              -p 8080:8080 \
              --restart=always \
              --env-file /home/${{ secrets.VM_USER }}/.env \
              --name newservice \
              $IMAGE_NAME
